application: chart-markup
version: 1
runtime: python
api_version: 1

handlers:
- url: /fxbook
  script: fxbook.py

- url: /test
  script: test-fx.py

- url: /my-account
  script: my-account.py

- url: /myfxhistory
  script: myfxhistory.py

- url: /css
  static_dir: css