application: chart-markup
version: 1
runtime: python
api_version: 1

handlers:
- url: /fxbook
  script: fxbook.py

- url: /my-account
  script: my-account.py

- url: /fetch-myhist
  script: fetch-myhist.py

- url: /css
  static_dir: css

- url: /wipe
  script: wipe.py

- url: /test
  script: test.py